manojpanta/Bike-Share

app/models/accessory.rb, app/models/accessory_order.rb, app/models/order.rb, app/models/user.rb, db/migrate/20180527002609_add_user_to_orders.rb, db/migrate/20180527003254_create_accessory_orders.rb, db/schema.rb, spec/models/accessory_order_spec.rb, spec/models/accessory_spec.rb, spec/models/order_spec.rb, spec/models/user_spec.rb
adds relationships to user and accessory
=> Order relation

app/controllers/sessions_controller.rb, app/views/sessions/new.html.erb, config/routes.rb, spec/features/user/user_can_login_spec.rb, spec/features/user/visitor_can_create_account_spec.rb
=> users can login

config/routes.rb
Adds functionality for visitor stations index. Visitors see all stations when visiting stations index.
=> changes through git rebase

app/controllers/stations_controller.rb, app/views/stations/show.html.erb, config/routes.rb, spec/features/visitors/visitor_sees_a_list_of_stations_spec.rb, spec/features/visitors/visitor_sees_a_station_show_page_spec.rb
creates visitor show page for station
=> Visitor show

app/controllers/sessions_controller.rb, spec/features/user/user_can_login_spec.rb
Logged in user can click logout link
they go to home screen and see a login link
=> User logout

app/views/sessions/new.html.erb, app/views/users/new.html.erb
Changes textfields to secure password fields
=> uses passwordfields

public/404.html, spec/features/user/user_can_login_spec.rb, spec/features/user/user_cannot_see_other_iser_info_spec.rb
Users cannot view other users info or visit admin pages
=> User authorization

Gemfile, Gemfile.lock, app/controllers/stations_controller.rb, app/controllers/trips_controller.rb, app/models/station.rb, app/views/stations/index.html.erb, app/views/trips/index.html.erb, config/routes.rb, spec/features/trips/visitor_sees_a_list_of_trips_spec.rb, spec/features/visitors/visitor_sees_a_station_show_page_spec.rb, spec/models/station_spec.rb
Adds trips index with all attributes and only 30 trips show with link to see next page of trips.
=> Trips index

app/controllers/trips_controller.rb, app/views/trips/show.html.erb, config/routes.rb, spec/features/trips/visitor_sees_one_trip_spec.rb
=> 5 trip show

app/controllers/orders_controller.rb, app/models/accessory_order.rb, app/models/order.rb, app/views/orders/show.html.erb, app/views/users/show.html.erb, config/routes.rb, spec/features/orders/user_can_view_orders_spec.rb, spec/models/accessory_order_spec.rb, spec/models/order_spec.rb
User can see their orders
They can navigate there from the dashboard
They can see the items, quantity and subtotal of each item
They can see status, total cost, and timestamps
=> User order view

app/controllers/admin/stations_controller.rb, app/views/admin/accessories/_form.html.erb, app/views/admin/stations/_form.html.erb, app/views/admin/stations/new.html.erb, config/routes.rb, spec/features/stations/admin_user_can_create_new_station_spec.rb
just created pr for admin station new
=> done with admin station new

app/controllers/admin/stations_controller.rb, app/views/admin/stations/edit.html.erb, spec/features/stations/admin_user_can_edit_station_spec.rb
created pr for admin station edit
=> create admin station edit functionality

app/controllers/admin/stations_controller.rb, app/views/stations/show.html.erb, spec/features/stations/admin_user_can_edit_and_delete_station_from_station_show_page_spec.rb
Created edit and delete functionality for admin on station show page.
=> creates edit and delete for admin on station show page

app/views/stations/index.html.erb, spec/features/stations/admin_user_can_delete_and_edit_station_from_station_index_spec.rb
added edit and delete functionality for admin on station index page
=> Admin Station Index

app/views/trips/index.html.erb, config/routes.rb, spec/features/trips/admin_sees_options_to_edit_and_delete_trips_from_index_spec.rb
=> Admin trips index

app/controllers/admin/trips_controller.rb, app/views/admin/trips/_form.html.erb, app/views/admin/trips/edit.html.erb, spec/features/trips/admin_can_see_edit_and_delete_button_next_to_trip_in_trip_show_page_spec.rb
added delete functionality to trip show for a admin
=> admin trip show edit delete

app/controllers/users_controller.rb, app/views/users/_form.html.erb, app/views/users/edit.html.erb, app/views/users/show.html.erb, config/routes.rb, spec/features/user/user_can_edit_their_info_spec.rb
Users and admins can edit their information
users cannot edit the info of another user
=> User admin edit auth

app/controllers/orders_controller.rb, app/views/orders/show.html.erb, spec/features/orders/admin_user_can_see_orders_spec.rb, spec/features/orders/user_can_view_orders_spec.rb
Admins can view all orders
They see user name and address plus all user info
Users can only see their own orders
=> Admin order show

app/controllers/application_controller.rb, app/views/layouts/application.html.erb
Adds trips to navbar
Adds admin dashboard to navbar
=> adds navbar functionality

app/controllers/admin/accessories_controller.rb, app/controllers/trips_controller.rb, app/views/accessories/index.html.erb, app/views/accessories/show.html.erb, app/views/admin/accessories/edit.html.erb, db/seeds.rb, spec/features/accessories/admin_can_create_new_accessory_spec.rb, spec/features/accessories/admin_can_edit_accessory_spec.rb, spec/features/accessories/admin_can_navigate_to_accessory_show_page_from_accessories_index_spec.rb
added seed data for accessories
=> Seed For Accessories

app/controllers/admin/accessories_controller.rb, app/controllers/sessions_controller.rb, app/views/accessories/index.html.erb, app/views/accessories/show.html.erb, app/views/layouts/application.html.erb, app/views/trips/index.html.erb, config/routes.rb, db/seeds.rb, spec/features/accessories/admin_can_retire_accessory_spec.rb, spec/features/trips/admin_can_create_new_trip_from_trip_index_page_spec.rb, spec/features/trips/admin_can_see_edit_and_delete_button_next_to_trip_in_trip_show_page_spec.rb, spec/features/trips/admin_sees_options_to_edit_and_delete_trips_from_index_spec.rb
added test and functionality for retire and reactivate on accessories
=> Add Retire and Reactivate

spec/features/admin/admin_login_spec.rb
on login admin goes to admin dashboard
=> admin goes to dashboard at login

app/controllers/admin/accessories_controller.rb, app/controllers/stations_controller.rb, app/models/station.rb, app/views/stations/dashboard.html.erb, spec/features/stations_dashboard_spec.rb, spec/models/station_spec.rb
added table and link to stations dashboard page.
=> Stations dashboard manoj

app/assets/stylesheets/application.css, app/views/accessories/index.html.erb, app/views/stations/dashboard.html.erb, app/views/stations/index.html.erb
=> PR for accessories page 

app/assets/stylesheets/application.css, app/views/accessories/index.html.erb, spec/features/stations/admin_user_can_delete_and_edit_station_from_station_index_spec.rb
styles buttons on admin bike shop
=> Css admin bike

app/controllers/stations_controller.rb, app/models/station.rb, app/views/stations/show.html.erb, app/views/users/show.html.erb, spec/features/stations/user_can_see_a_station_spec.rb, spec/features/trips/admin_sees_new_trip_spec.rb, spec/models/station_spec.rb, spec/models/user_spec.rb
=> 36 user station show

app/controllers/admin/accessories_controller.rb, app/controllers/admin/orders_controller.rb, app/views/accessories/index.html.erb, spec/features/accessories/admin_can_retire_accessory_spec.rb, spec/features/user_can_add_accessories_to_their_cart_spec.rb
Added redirect back and modify test expectations accordingly.
=> PR , Adding Redirect Back

app/controllers/trips_controller.rb, app/views/trips/dashboard.html.erb, config/routes.rb, spec/features/trips/admin_sees_new_trip_spec.rb, spec/features/trips/user_visits_station_dashboard_spec.rb
=> Trips dashboard

README.md, app/channels/application_cable/channel.rb, app/channels/application_cable/connection.rb, app/jobs/application_job.rb, app/mailers/application_mailer.rb
=> Simplecov fix
